# Outputting
permalink:     none

#Enable Automatic Sitemap Generation
gems:
  - jekyll-sitemap

 # Avoid pygments.rb
highlighter: pygments

#Enalbe MathJax
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "with_toc_data", "no_intra_emphasis"]